// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKzt28QKvmQguKOvdfTO1OXKOedyo1uE',
    appId: '1:241349491554:web:2502a29a9ef7d41436ca3b',
    messagingSenderId: '241349491554',
    projectId: 'genesis-app-343dc',
    authDomain: 'genesis-app-343dc.firebaseapp.com',
    storageBucket: 'genesis-app-343dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd6LRAvggy2Pf_wfbBHBj5H3hbtLOdZnM',
    appId: '1:241349491554:android:593ff85942c675aa36ca3b',
    messagingSenderId: '241349491554',
    projectId: 'genesis-app-343dc',
    storageBucket: 'genesis-app-343dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IW0onHDMl09ZjC8DtmsFMLW5hgnMQYc',
    appId: '1:241349491554:ios:8626714c571b0dec36ca3b',
    messagingSenderId: '241349491554',
    projectId: 'genesis-app-343dc',
    storageBucket: 'genesis-app-343dc.firebasestorage.app',
    iosBundleId: 'com.hbox.genesisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IW0onHDMl09ZjC8DtmsFMLW5hgnMQYc',
    appId: '1:241349491554:ios:668d94992927e8d036ca3b',
    messagingSenderId: '241349491554',
    projectId: 'genesis-app-343dc',
    storageBucket: 'genesis-app-343dc.firebasestorage.app',
    iosBundleId: 'com.example.bibleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGKzt28QKvmQguKOvdfTO1OXKOedyo1uE',
    appId: '1:241349491554:web:772375a2e0e0ed2d36ca3b',
    messagingSenderId: '241349491554',
    projectId: 'genesis-app-343dc',
    authDomain: 'genesis-app-343dc.firebaseapp.com',
    storageBucket: 'genesis-app-343dc.firebasestorage.app',
  );
}
